apiVersion: v1
baseDomain: acepod.com
compute:
- architecture: amd64
  hyperthreading: Enabled
  name: worker
  platform: {}
  replicas: 3
controlPlane:
  architecture: amd64
  hyperthreading: Enabled
  name: master
  platform: {}
  replicas: 3
metadata:
  creationTimestamp: null
  name: ocp-cl02
networking:
  clusterNetwork:
  - cidr: 10.128.0.0/14
    hostPrefix: 23
  machineNetwork:
  - cidr: 10.0.0.0/16
  networkType: antrea
  serviceNetwork:
  - 172.30.0.0/16
platform:
  vsphere:
    apiVIP: 10.114.1.191
    cluster: CL01-MGMT
    datacenter: SUN01
    defaultDatastore: vsanDatastore
    ingressVIP: 10.114.1.192
    network: VDS01-VLAN114-Workload-Net
    password: VMware1!
    username: administrator@vsphere.local
    vCenter: sun01-vcenter00.acepod.com
publish: External
pullSecret: '{"auths":{"cloud.openshift.com":{"auth":"b3BlbnNoaWZ0LXJlbGVhc2UtZGV2K29jbV9hY2Nlc3NfMWI5MDZkMWVhOThiNGQyZDgxMDA3NGI3MTllY2YyMzg6MENUNUM3TDQwQjRMTjdDMlhBSFg0T1hHVjU2TFRBRjNRU0YwVFYzMlA1RFYzUVNEM05JVjdRNDBWRzQ2Wjk3MA==","email":"vincent@acepod.com"},"quay.io":{"auth":"b3BlbnNoaWZ0LXJlbGVhc2UtZGV2K29jbV9hY2Nlc3NfMWI5MDZkMWVhOThiNGQyZDgxMDA3NGI3MTllY2YyMzg6MENUNUM3TDQwQjRMTjdDMlhBSFg0T1hHVjU2TFRBRjNRU0YwVFYzMlA1RFYzUVNEM05JVjdRNDBWRzQ2Wjk3MA==","email":"vincent@acepod.com"},"registry.connect.redhat.com":{"auth":"NTI0MDAzOTh8dWhjLTFnN0c5aUtOYm1Pa0NCWWdFNkF6bHlUaEQwczpleUpoYkdjaU9pSlNVelV4TWlKOS5leUp6ZFdJaU9pSmtNRE5qTldRM1pXUXdNRE0wTWpZMVlXWm1PRFZqWmpjd05HUmhNbU01WlNKOS5OSGlmV013enh6WnVSRXAxdGt4Z3pmVk1heDNjbkVtQlJaYjNQTHNLRXhqcFAxazNZLU55di1va3I0ZklEdEhNcDNqbEJ3c2FYS3VVWDdTT2R2R2pqcWYxYkZhaUtDNkhSR1ZiLVdaeW5VaGZvYnJXajNYWDR6SlczbmRKcmN0ZGhaSTEzR0hIUzVrdTV0Z05OYnIzdGFnOVQ0dkxNRk5NaTdUdGZia2xJUGFMZlpXZ2g2V1pnOERvdHF2eUM2ZUdZYjBBNm5zTUYwekg5MjhXQkdIZ0NYSUhQd2lRMThETjJaSnRmbTlaMWtiWXNfT0I1b05YR055bWxfZDY5UWo0S2Q1dTZVY05DdVZmM1o0aHl2Q0hmb3hEREdsVThKVmtUOG9DWlN2aTY1NnN3RnVudXBlYUhmclFGWUNRaEVTcjhhOGlvWXFBRldZTjJfMG1sMlZwUGdzQ3lrbHpReTVaVnFlMndRc19LQmxmcVBjTThpd2ZBMmYteWwtbnU0ak1SRG5LaXpOWVk5RXQzS21UaU9ZczhoNUlWS1BjNkl6cERESEJTbUdpTGd3YUQzeFNyTmhETUhOX3BEb0huNTdhWTJQekExaThMTmNUUllWQ0hqcWdQaXZDVERLRDhGUERvLVB4QjB3WWpFbnhXaVl0cHRQdUtaUUtpMm14MmZ2T2RFMFRfNGw1RjRob2NoSVBSOEhTSExZMTJfZVVwQzBkTEpDR21FMzdIY3o5UFp1cU1jbWNsS3BwbW9XQ0JmcVNLem9UTHRlUEhPOTZpR3NHajl5em9xR0I1QUJBdlFuX1VJYmlYa09zZTFDWkJVNG1xU2pRaUZRN20zU0t0X3lzMllHaWd4YjN0ekhWVEF2b2JLRVF3SWlaQ1o1NXNPelRvZzhlUlVqWUxHaw==","email":"vincent@acepod.com"},"registry.redhat.io":{"auth":"NTI0MDAzOTh8dWhjLTFnN0c5aUtOYm1Pa0NCWWdFNkF6bHlUaEQwczpleUpoYkdjaU9pSlNVelV4TWlKOS5leUp6ZFdJaU9pSmtNRE5qTldRM1pXUXdNRE0wTWpZMVlXWm1PRFZqWmpjd05HUmhNbU01WlNKOS5OSGlmV013enh6WnVSRXAxdGt4Z3pmVk1heDNjbkVtQlJaYjNQTHNLRXhqcFAxazNZLU55di1va3I0ZklEdEhNcDNqbEJ3c2FYS3VVWDdTT2R2R2pqcWYxYkZhaUtDNkhSR1ZiLVdaeW5VaGZvYnJXajNYWDR6SlczbmRKcmN0ZGhaSTEzR0hIUzVrdTV0Z05OYnIzdGFnOVQ0dkxNRk5NaTdUdGZia2xJUGFMZlpXZ2g2V1pnOERvdHF2eUM2ZUdZYjBBNm5zTUYwekg5MjhXQkdIZ0NYSUhQd2lRMThETjJaSnRmbTlaMWtiWXNfT0I1b05YR055bWxfZDY5UWo0S2Q1dTZVY05DdVZmM1o0aHl2Q0hmb3hEREdsVThKVmtUOG9DWlN2aTY1NnN3RnVudXBlYUhmclFGWUNRaEVTcjhhOGlvWXFBRldZTjJfMG1sMlZwUGdzQ3lrbHpReTVaVnFlMndRc19LQmxmcVBjTThpd2ZBMmYteWwtbnU0ak1SRG5LaXpOWVk5RXQzS21UaU9ZczhoNUlWS1BjNkl6cERESEJTbUdpTGd3YUQzeFNyTmhETUhOX3BEb0huNTdhWTJQekExaThMTmNUUllWQ0hqcWdQaXZDVERLRDhGUERvLVB4QjB3WWpFbnhXaVl0cHRQdUtaUUtpMm14MmZ2T2RFMFRfNGw1RjRob2NoSVBSOEhTSExZMTJfZVVwQzBkTEpDR21FMzdIY3o5UFp1cU1jbWNsS3BwbW9XQ0JmcVNLem9UTHRlUEhPOTZpR3NHajl5em9xR0I1QUJBdlFuX1VJYmlYa09zZTFDWkJVNG1xU2pRaUZRN20zU0t0X3lzMllHaWd4YjN0ekhWVEF2b2JLRVF3SWlaQ1o1NXNPelRvZzhlUlVqWUxHaw==","email":"vincent@acepod.com"}}}'
sshKey: |
  ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDdEWyxrTz91+YfNuUHoaFVFWJFUp2lZA3Dwh2MU49UNkZwM3QilwdCNCo8N257FvMkSEakEPpJhvFEH2YRvSzIQp08sSfemv/fdGgkUtRavdmnR76TNQVp6AsAaAKrIbAVyBMT+QDTmtyiktuA847yflm0tIEkjSGd6K0osKADkiMPk2fDozGAlOxZYYi8z4cD5/NCHWCYI+h94JW6EVZVPdzBtiuJ9l5fMC+nqU1dkaN6i59jkVDr+BWKhDwhJ6zJlUsRyLU+i6UFXnOcBsus65nJIrVoG3iVa8MYUpfOJ3BmmRjbyZSW31wfF3G1abGD46a9VrzrJWJ5HQr7HaiX root@localhost.localdomain
