apiVersion: v1
kind: ConfigMap
metadata:
  name: root-ca
  namespace: kube-system
data:
  ca.crt: |
    -----BEGIN CERTIFICATE-----
    MIIDEDCCAfigAwIBAgIIOL9TCVxLLiowDQYJKoZIhvcNAQELBQAwJjESMBAGA1UE
    CxMJb3BlbnNoaWZ0MRAwDgYDVQQDEwdyb290LWNhMB4XDTIxMTExMTAyMTk0NFoX
    DTMxMTEwOTAyMTk0NFowJjESMBAGA1UECxMJb3BlbnNoaWZ0MRAwDgYDVQQDEwdy
    b290LWNhMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA5rLh0VqqueBe
    g93CZMfUB/ZzR/uZEJ9UgP5VmGBbM8Bs8oWlOw4RqIVeHHSl+2bwrptgiOWxLTB9
    041uuvGbwGpXhkBYzH9AU+kaetGr1GqWk3SO/F2V3T2AVMHcvxr5xFbPnQcTPrG8
    +Oq1Jd6OKUeOuus/PVPPmGz3gxGChdFUtq40L+eY3uvX9v5wysJZS6Bh25TSM1i3
    v301gQ1oSAf+qVkFGTv4dmaj+0h9NfLM9qxiYEBw7ViCFxE0fJVpxyiNf4+D2uRU
    ZgKsPF2bgi40pvaqieZgvI07jmGItXEuIE3ggYEj9nJt/KaMsfIgPwFXL0FSf9UO
    Rp/s7goeTQIDAQABo0IwQDAOBgNVHQ8BAf8EBAMCAqQwDwYDVR0TAQH/BAUwAwEB
    /zAdBgNVHQ4EFgQURBR75QfvMG1xBYB3YjUvGC6K3NQwDQYJKoZIhvcNAQELBQAD
    ggEBAAAyjRboYiWCMmFPboj+VZyq3pI62VBaRig8PedB0q7qqdYw6PyLkKx3ngEt
    N5bC9w3+mNAjBCL01ur6pNDpNZOHsW1fxV1p7FOZKNk08zi+yXP1bHk/K/DYUL6o
    FNh9MvOrQoT41Fxa3Jn4YHHigautLPVNIQHAOmp8ASBO/5+zdqTGQ4MWU8TfuTJN
    dBePWy12AVArHXfpRP/NcQUnfFfAcHw+SvworEiKuoEOXffH5Vp/5JAV/Uapaoc/
    3aviegfrDGLGTrs8CHnZ1HSFTA1sip2+r2ayW5wijBHWM+i5cIrLNbDfCm+Xi7HT
    gEE5Ujeq4hi8pJKb7nktxseXoE8=
    -----END CERTIFICATE-----
    
