apiVersion: machine.openshift.io/v1beta1
kind: MachineSet
metadata:
  creationTimestamp: null
  labels:
    machine.openshift.io/cluster-api-cluster: ocp-cl02-xdqkk
  name: ocp-cl02-xdqkk-worker
  namespace: openshift-machine-api
spec:
  replicas: 3
  selector:
    matchLabels:
      machine.openshift.io/cluster-api-cluster: ocp-cl02-xdqkk
      machine.openshift.io/cluster-api-machineset: ocp-cl02-xdqkk-worker
  template:
    metadata:
      labels:
        machine.openshift.io/cluster-api-cluster: ocp-cl02-xdqkk
        machine.openshift.io/cluster-api-machine-role: worker
        machine.openshift.io/cluster-api-machine-type: worker
        machine.openshift.io/cluster-api-machineset: ocp-cl02-xdqkk-worker
    spec:
      metadata: {}
      providerSpec:
        value:
          apiVersion: vsphereprovider.openshift.io/v1beta1
          credentialsSecret:
            name: vsphere-cloud-credentials
          diskGiB: 120
          kind: VSphereMachineProviderSpec
          memoryMiB: 8192
          metadata:
            creationTimestamp: null
          network:
            devices:
            - networkName: VDS01-VLAN114-Workload-Net
          numCPUs: 2
          numCoresPerSocket: 2
          snapshot: ""
          template: ocp-cl02-xdqkk-rhcos
          userDataSecret:
            name: worker-user-data
          workspace:
            datacenter: SUN01
            datastore: vsanDatastore
            folder: /SUN01/vm/ocp-cl02-xdqkk
            resourcePool: /SUN01/host/CL01-MGMT/Resources
            server: sun01-vcenter00.acepod.com
status:
  replicas: 0
